### ISSUE TITLE
hashSum wont work for other text files

### ISSUE THREAD

**Issue by ghost** [karroshuang/Huang_Narayanswamy_Smith_CSCI2270_FinalProject#3]
The hashSum function is seems like it would only work with the "items.txt" file.  Instead of calculating the hash sum of the category string, the function uses if/else statements to see if the string matches one of the categories in the text file. This limits the program to only run text files with these 8 categories ("Health and Beauty", "Sports", etc...).  A text file with a different category/categories, such as "Camping Gear" or "bikes" would not work.

**Comment by karroshuang** [comment]
You bring up a good point. Since our array is fixed to a size of 10, we cannot add additional categories to it like Camping Gear or Bikes at any point in the program. Therefore we decided on 10 categories to use to store our items. I will update the readme to specify that the user only gets to work with the 10 categories that are preset, and if they want to import their own text file it will have to contain only items in those categories.
